### PR TITLE
Add some documentation about typeWriteMode

### PR DESCRIPTION
**Pull request by ruoat**
I could not find any documentation about typeWriteMode but found the feature from sources :)

### CODE REVIEW

**Comment by komu** [comment]
Yeah, it's was not documented on purpose because it was added as an incubating experiment and I wasn't sure I want to commit to supporting it. The long term plan is to change the default and probably get rid of the flag completely. Perhaps I could even do it today.

We've been using the interface-mode exclusively and I don't think anyone will miss the old mode, but technically it is a breaking change so I didn't want to rush things. Do you thing you'll have any problems if the default would change?

**Comment by ruoat** [comment]
I just POCced Apina for our project yesterday. I showed the generated typescript to colleague and he said that it would be better if it generated interfaces instead. And eventually found that it is possible. So we do not have anything against if the default was INTERFACE. If you are going to implement that change this pr can be closed as "stupid idea" ;-)

**Comment by komu** [comment]
There's actually one good reason for generating classes: if you generate interfaces, then you don't get any runtime representation of the type and TypeScript compiler issue light warnings when you refer the type from an annotated field.

For example:

```typescript
@Input()
foo: Foo:
```

When using annotations, TypeScript would like to create dynamic metadata for the field and pass `Foo` to it as a parameter, but if `Foo` is an interface instead of class, there's nothing at runtime to pass. So if you pass apina-generated objects as properties for Angular components, you end up with these warnings from the compiler. You can safely ignore those because Angular doesn't actually need the runtime types for anything, but they are slightly annoying.

On the other hand, classes mostly function as interfaces because TypeScript is structurally typed instead of nominally typed:

```typescript
class Foo {
    foo: string;
}

interface Bar {
    Bar: string;
}

const myFoo: Foo = { foo: "quux" };
const myBar: Bar = { bar: "quux" };
```

This was the reason why Apina originally generated classes: you don't actually ever need to instantiate the classes, but can use them just like interfaces. It's just that you get something extra for them as well and it keeps compiler happy when using annotations.

Alas, when TypeScript compiler came stricter, it got checks to verify that all fields are correctly initialized the constructor. So using recent compile versions, `Foo` given above would pass the compiler at `strict: true´ anymore. So now the downsides of the original hack are bigger than the upsides and I'll change the default.

This was probably way more detailed than you wanted. :smile:

**Comment by ruoat** [comment]
Actually this answer was very insightful. Thanks! 🙂

**Comment by komu** [comment]
I just released `0.13.0`. Nothing else changes apart from `INTERFACE` being the default mode.

If someone starts complaining that things broke and they really need the old mode, I'll document the way to get the old functionality. Otherwise I'll remove it completely at some point in the future.

**Pull request closed without merging**
